MYSQL_HOST="127.0.0.1"
MYSQL_PORT=3306
MYSQL_USER=isucon
MYSQL_DBNAME=isucondition
MYSQL_PASS=isucon
POST_ISUCONDITION_TARGET_BASE_URL="https://app-1.churadata-isucon.cc"

MYSQL_DRIVER_POSTFIX=:logger
CPU_PROFILE_FILE=/tmp/cpu.pprof